
// ------------- FILE HEADER -------------
// Author ✅: 
// Assignment ✅:
// Date ✅:
// Citations: 


// ------------- CODE -------------
// https://en.cppreference.com/w/cpp/preprocessor/include
#include <iostream>
//cout|
// https://en.cppreference.com/w/cpp/io/basic_ostream
// https://en.cppreference.com/w/cpp/header/iostream
// https://en.cppreference.com/w/cpp/language/namespace
using namespace std;

// Function prototypes (if any)


// Main function
// https://en.cppreference.com/w/cpp/language/main_function.html
int main() {
  // C++ Generated by copilot generated from design
  // https://en.cppreference.com/w/cpp/io/basic_ostream
  // https://en.cppreference.com/w/cpp/io/manip/endl
  cout << "Welcome to my Weekly Payroll program!!" << endl;
 
  cout << "Enter your employee ID number (numbers only): ";
// https://en.cppreference.com/w/cpp/language/types#Fundamental_types
int employeeID = 0; 
// https://en.cppreference.com/w/cpp/io/basic_istream
cin >> employeeID; 
 
cout << "Enter number of hours worked (whole numbers): ";
int employeeHours = 0;
cin >> employeeHours;

cout << "Enter the hourly rate: ";
int USDPerHour = 0;
cin >> USDPerHour;

cout << "Enter the federal withholding rate: ";
int integerwithholdingRate = 0;
cin >> integerwithholdingRate;

// Calculations
// https://en.cppreference.com/w/cpp/language/types#Fundamental_types
double grosspayUSD = employeeHours * USDPerHour;
double decimalWithholdingRate = integerwithholdingRate / 100.0;
double federalTaxWithholdingUSD = grosspayUSD * decimalWithholdingRate;
double netPayUSD = grosspayUSD - federalTaxWithholdingUSD;

// Output
cout << "Your Payroll Summary:" << endl; 
cout << "Total Gross Pay: $" << grosspayUSD << endl;
cout << "Federal Tax Withholding: $" << federalTaxWithholdingUSD << endl;
cout << "Net Pay: $" << netPayUSD << endl;  
cout << "Thank you for using my Weekly Payroll program!!" << endl;

  // https://en.cppreference.com/w/cpp/language/return
  return 0;
}

// Function implementations (if any)


// ------------- DESIGN -------------
/*
Program Name:
Tax Calculator

Program Description:
During September, businesses across the United States take time to thank their payroll teams and reflect on all of the successful paydays of the past year. While technology has made it easier than ever for HR teams to pay their employees, crunching the numbers can still be a laborious task for payroll professionals. National Payroll Week serves as a reminder that there are dedicated professionals working hard everyday to ensure we get paid accurately and on time.

Design:
A. INPUT
int employeeID = 0;
int employeeHours = 0;
int USDPerHour = 0;
int integerwithholdingRate = 0;

B. OUTPUT
double grosspayUSD = 0.0;
double federalTaxWithholdingUSD = 0.0;
DATA netPayUSD = 0.0;

C. CALCULATIONS
First calculate the total gross pay from the hours worked and the hourly rate inputs. 
grosspayUSD = employeeHours * USDPerHour;
double decimalWitholdingRate = integerwithholdingRate / 100.0;
federalwithholdingRate = grosspayUSD * federalwithholdingRate;
netPayUSD = grosspayUSD - federalwithholdingRate

D. LOGIC and ALGORITHMS
Welcome "Welcome to my Weekly Payroll program!!"

Prompt "Enter your employee ID number (numbers only): "
Input employeeID

Prompt "Enter number of hours worked (whole numbers): "
Input employeeHours

Prompt "Enter the hourly rate: "
Input USDPerHour

Prompt "Enter the federal withholding rate: "
Input federalwithholdingRatePercent

Do Calculations

Heading "Your Payroll Summary:"

Label "Gross Pay: "
DATA grosspayUSD

Label "Federal Tax Withholding: "
Data federalTaxWithholdingUSD

Label "Net Pay: "
DATA netPayUSD

Goodbye "Thank you for using my Weekly Payroll program!!"

FLOWCHART in drawio format generated by copilot from section D
https://drive.google.com/file/d/16qYIoYRtVUy8DwMl7i5Q0BrnAvlQSx-7/view?usp=sharing

SAMPLE RUNS
Welcome to my Weekly Payroll program!!
Enter your employee ID number (numbers only): 34567
Enter number of hours worked (whole numbers): 40
Enter the hourly rate: 17
Enter the federal withholding rate: 15
Your Payroll Summary:
Total Gross Pay: $680
Federal Tax Withholding: $102
Net Pay: $578
Thank you for using my Weekly Payroll program!!



Welcome to my Weekly Payroll program!!
Enter your employee ID number (numbers only): 12345
Enter number of hours worked (whole numbers): 30
Enter the hourly rate: 22
Enter the federal withholding rate: 10

Your Payroll Summary:
Total Gross Pay: $660
Federal Tax Withholding: $66
Net Pay: $594

Thank you for using my Weekly Payroll program!!
*/